server:
  port: 8081

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
spring:
  cloud:
    stream:
      function:
        definition: process
      bindings:
        process-in-0:
          destination: publisher_channel
        process-out-0:
          destination: subscriber_channel
