  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/rabbitdb
      username: root
      password: root
    cloud:
      stream:
        function:
          definition: subscribe
        bindings:
          subscribe-in-0:
            destination: subscriber_channel
  server:
    port: 8082
  jpa:
    hibernate:
      ddl-auto: create

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


